mkdir ./data/data
mkdir ./data/models
mkdir ./data/data/core_chain_pairwise
mkdir ./data/data/core_chain_pairwise/lcquad
mkdir ./data/data/core_chain_pairwise/qald
mkdir ./data/data/core_chain_pointwise/
mkdir ./data/data/core_chain_pointwise/lcquad
mkdir ./data/data/core_chain_pointwise/qald
mkdir ./data/data/qald
mkdir ./data/data/lcquad
mkdir ./data/data/common
mkdir ./data/data/transfer-a
mkdir ./data/data/transfer-b
mkdir ./data/data/transfer-c
mkdir ./data/data/rdf
mkdir ./data/data/rdf/lcquad
mkdir ./data/data/rdf/qald
mkdir ./models/core_chain
mkdir ./models/birnn_dot
mkdir ./models/birnn_dense
mkdir ./models/birnn_dense_sigmoid
mkdir ./models/two_birnn_dot
mkdir ./models/parikh
mkdir ./models/parikh_dot
mkdir ./models/maheshwari
mkdir ./models/cnn
mkdir ./models/birnn_dot/lcquad
mkdir ./models/birnn_dot/qald
mkdir ./models/birnn_dot/transfer-a
mkdir ./models/birnn_dot/transfer-b
mkdir ./models/birnn_dot/transfer-c
mkdir ./models/birnn_dot/transfer-proper-qald
mkdir ./models/intent
mkdir ./models/intent/lcquad
mkdir ./models/intent/qald
mkdir ./models/type_existence
mkdir ./models/type_existence/lcquad
mkdir ./models/type_existence/qald